version: '3.8'
services:
  api-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: go-nat-dev
    volumes:
      - './:/app'
    working_dir: /app
    environment:
      - PORT=${PORT} 
    ports:
      - 8001:${PORT}
    env_file:
      - .env
    # network_mode: bridge
    # links:
    #   - database
    #   - rabbitmq
