version: '3.8'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: go-nat-dev
    volumes:
      - './:/app'
    working_dir: /app
    environment:
      - PORT=${PORT} 
    ports:
      - 3000:${PORT}
    env_file:
      - .env
    # links:
    #   - database
    #   - rabbitmq