version: '3.8'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: microservices
    volumes:
      - './:/app'
    working_dir: /app
    ports:
      - 3000:3000
    env_file:
      - .env
    # links:
    #   - database
    #   - rabbitmq