package main

import (
	"log"

	"github.com/gofiber/fiber/v2"
	"github.com/gofiber/swagger"
	_ "github.com/xkritti/go-nat-project/micriservice/docs" // docs is generated by Swag CLI, you have to import it.
)

func main() {
	app := fiber.New()

	app.Get("/swagger/*", swagger.HandlerDefault) // default

	api := app.Group("/api")

	api.Get("/", func(c *fiber.Ctx) error {
		return c.SendString("Hello, World 👋!")
	})

	log.Fatal(app.Listen(":3000"))
}
