name: CI/CD for Develop Branch

on:
  push:
    branches:
      - develop

jobs:
  Deploy:
    runs-on: [self-hosted]
    environment: demo
    
    env:
      PORT: ${{secrets.PORT}}
      DB_HOST: ${{secrets.DB_HOST}}
      DB_PORT: ${{secrets.DB_PORT}}
      DB_USERNAME: ${{secrets.DB_USERNAME}}
      DB_PASSWORD: ${{secrets.DB_PASSWORD}}
      DB_DATABASE: ${{secrets.DB_DATABASE}}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          clean: false

      - name: Create .env
        run: |
          cat << EOF > .env
          PORT=$PORT
          DB_HOST=$DB_HOST
          DB_PORT=$DB_PORT
          DB_USERNAME=$DB_USERNAME
          DB_PASSWORD=$DB_PASSWORD
          DB_DATABASE=$DB_DATABASE
          EOF
          
      # - name: Show .env Contents
      #   run: cat .env

      - name: Run Docker Compose Dev
      # because we are using 2 Dockerfiles, we need to specify the docker-compose.yml file
      # by default docker compose up , i should be use the default docker-compose.yml file
        run: docker compose -f docker-compose.yml up -d --build

      - name: Clear Unused Containers
        run: docker system prune -f
