name: CI/CD for Develop Branch

on:
  push:
    branches:
      - develop

jobs:
  Deploy:
    runs-on: [self-hosted]
    environment: demo
    
    env:
      PORT: ${{secrets.PORT}}
      DB_HOST: ${{secrets.PG_HOST}}
      DB_PORT: ${{secrets.PG_PORT}}
      DB_USERNAME: ${{secrets.PG_USERNAME}}
      DB_PASSWORD: ${{secrets.PG_PASSWORD}}
      DB_DATABASE: ${{secrets.PG_DATABASE}}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          clean: false

      - name: Create .env
        run: |
          cat << EOF > .env
          PORT=$PORT
          DB_HOST=$PG_HOST
          DB_PORT=$PG_PORT
          DB_USERNAME=$PG_USERNAME
          DB_PASSWORD=$PG_PASSWORD
          DB_DATABASE=$PG_DATABASE
          EOF
          
      # - name: Show .env Contents
      #   run: cat .env

      - name: Run Docker Compose Dev
        run: docker compose -f docker-compose.dev.yml up -d --build

      - name: Clear Unused Containers
        run: docker system prune -f
