name: CI/CD for Develop Branch

on:
  push:
    branches:
      - develop

jobs:
  Deploy:
    runs-on: [self-hosted]
    
    env:
      PORT: ${{env.PORT}}
      PG_HOST: ${{env.PG_HOST}}
      PG_PORT: ${{env.PG_PORT}}
      PG_USERNAME: ${{env.PG_USERNAME}}
      PG_PASSWORD: ${{env.PG_PASSWORD}}
      PG_DATABASE: ${{env.PG_DATABASE}}
      SYNCHRONIZE: ${{env.SYNCHRONIZE}}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create .env
        run: |
          cat << EOF > .env
          PORT=$PORT
          PG_HOST=$PG_HOST
          PG_PORT=$PG_PORT
          PG_USERNAME=$PG_USERNAME
          PG_PASSWORD=$PG_PASSWORD
          PG_DATABASE=$PG_DATABASE
          SYNCHRONIZE=$SYNCHRONIZE
          EOF
          
      - name: Show .env Contents
        run: cat .env

      - name: Run Docker Compose Dev
        run: docker-compose -f docker-compose.dev.yml up -d --build

      - name: Clear Unused Containers
        run: docker system prune -f
